name: Verify Arduino
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build all sketches
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        board: "arduino:avr:mega:cpu=atmega2560"
        sketchDirectory: "wanderer"
        libraries: "wanderer/libraries"
