name: Verify Arduino
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build all sketches
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        board: "arduino:avr:mega:cpu=atmega2560"
        sketchDirectory: "wanderer"
